---
galaxy_info:
  author: Berry Langerak
  description: An Ansible role for installing and configuring PostgreSQL.
  company: Enrise
  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - trusty

categories:
- database
- database:sql

dependencies:
- enrise.locale